spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/docker_postgres
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true
logging:
  level:
    root: INFO

